### ISSUE TITLE
Add asmfmt beautifier for assembly language

### ISSUE THREAD

**Issue by stevenzeck** [Unibeautify/beautifier-asmfmt#1]
_From @lassik on October 7, 2018 17:35_

**Beautifier Details**
Name: asmfmt
Link to project/homepage: https://github.com/klauspost/asmfmt
Languages Supported: assembly language
How is it run (node, terminal, etc): external program with simple stdin->stdout pipe

**Additional context**
@Glavin001, please create a `beautifier-asmfmt` repo under the Unibeautify organization. I'll submit a PR to implement it.

_Copied from original issue: Unibeautify/unibeautify#198_

**Comment by stevenzeck** [comment]
@lassik

**Comment by lassik** [comment]
PR #2
